name: Monitor-Timer

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run logic
        env:
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
        run: python monitor.py
      - name: Save Result
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add last_title.txt
          git commit -m "Update last title" || exit 0
          git push
