name: Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libs
        run: pip install requests beautifulsoup4

      - name: Run
        env:
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          PYTHONUNBUFFERED: 1  # 强制 Python 立即输出每一行日志，不缓存
        run: python monitor.py

      - name: Auto Save State
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Save state"
          file_pattern: "notified_ids.txt"
